### ISSUE TITLE
Typo in package.json

### ISSUE THREAD

**Issue by Paul-Reed** [DeanCording/node-red-contrib-google-action#1]
https://github.com/DeanCording/node-red-contrib-google-action/blob/9b3b2d41eeb7342a455034fb98fbb78887928047/package.json#L27

Hi Dean, typo in git url gives a dead link when accessing your repo via npm.
`node-red-contrib-google.action.git` should be `node-red-contrib-google-action.git`

Paul

**Comment by DeanCording** [comment]
Thanks,

Fixed and new version published.

**Comment by Paul-Reed** [comment]
Dean, finally got some time to try this node, and it's working great (as a test-app).
I've done a quick video of it in action - https://photos.app.goo.gl/4E91ifXoDtN6JQKi2 and also posted in node-red's Slack channel - https://node-red.slack.com/archives/C0KM5QT0F/p1513544080000008
...Just a quick message to say thanks!

**Comment by DeanCording** [comment]
Thanks Paul,You can set a shortcut in Google Home to make it easier to invoke. I have set 'node red' as a shortcut for 'talk to my test app' so I just have to say 'ok Google, node red'.-------- Original Message --------Subject: Re: [DeanCording/node-red-contrib-google-action] Typo in package.json (#1)From: Paul To: DeanCording/node-red-contrib-google-action CC: Dean Cording ,State change Dean, finally got some time to try this node, and it's working great (as a test-app).
I've done a quick video of it in action - https://photos.app.goo.gl/4E91ifXoDtN6JQKi2 and also posted in node-red's Slack channel - https://node-red.slack.com/archives/C0KM5QT0F/p1513544080000008
...Just a quick message to say thanks!

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DeanCording/node-red-contrib-google-action","title":"DeanCording/node-red-contrib-google-action","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/DeanCording/node-red-contrib-google-action"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Paul-Reed in #1: Dean, finally got some time to try this node, and it's working great (as a test-app).\r\nI've done a quick video of it in action - https://photos.app.goo.gl/4E91ifXoDtN6JQKi2 and also posted in node-red's Slack channel - https://node-red.slack.com/archives/C0KM5QT0F/p1513544080000008\r\n...Just a quick message to say thanks!"}],"action":{"name":"View Issue","url":"https://github.com/DeanCording/node-red-contrib-google-action/issues/1#issuecomment-352287696"}}}

**Comment by Paul-Reed** [comment]
How do you set the shortcut? I haven't seen that option?

**Comment by DeanCording** [comment]
In the Google Home app it's under More Settings.-------- Original Message --------Subject: Re: [DeanCording/node-red-contrib-google-action] Typo in package.json (#1)From: Paul To: DeanCording/node-red-contrib-google-action CC: Dean Cording ,State change How do you set the shortcut? I haven't seen that option?

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DeanCording/node-red-contrib-google-action","title":"DeanCording/node-red-contrib-google-action","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/DeanCording/node-red-contrib-google-action"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Paul-Reed in #1: How do you set the shortcut? I haven't seen that option?"}],"action":{"name":"View Issue","url":"https://github.com/DeanCording/node-red-contrib-google-action/issues/1#issuecomment-352291166"}}}

**Comment by Paul-Reed** [comment]
OK, thanks.
