### ISSUE TITLE
WebHooks returns code 206

### ISSUE THREAD

**Issue by soloam** [DeanCording/node-red-contrib-google-action#9]
Hello, I've been trying to call NodeRed from google assistant, but I keep getting a error 206 and nothing appears on my debug.

If I put a TCP node and monitor port 8081 I can see the encrypted stream arriving to my nodered, but when I use the google actions node nothing happens. I added the .crt file and .key file to the configs of the node, but nothing happens, no errors, no output... nothing.

Who can i know what I'm doing wrong? Can it be the certificate problem?

I have the same problem with the forked node google actions to dialogflow,

Thank you

**Comment by DeanCording** [comment]
I believe that an error 206 is caused by a certificate problem.  Are the keys password protected?

**Comment by soloam** [comment]
What is the file type that node is expecting? The private key in .key file type and the certificate in .crt file type?

I have a certificate that I got, in the zip file I have 3 forlders and a file:

- **Folder Linux:**
  - domain_com.ca-bundle
- **Folder Root Certificates:**
  - AddTrustExternalCARoot.crt
  - COMODORSAAddTrustCA.crt
  - COMODORSADomainValidationSecureServerCA.crt
- **Folder Windows**
  - domain_com.p7b
- **File domain_com.crt**

Then I have a CSR key (-----BEGIN CERTIFICATE REQUEST-----), a Public Key (-----BEGIN PUBLIC KEY-----) and Private Key (-----BEGIN RSA PRIVATE KEY-----).

I added to the node red the domain_com.crt file and a file server.key with the Private Key.

Is this correct?

Thank you

**Comment by soloam** [comment]
Ok, I was able to make this work... But still not able to make Dialogflow work, any plan to make this work with Dialogflow? The fork seems to stoped in time and does not work.

Thank you for your help

**Comment by DeanCording** [comment]
This is intended to be the bare minimum node to enable Google Home devices to work with Node Red so that Node Red can take care of all of the dialog processing instead of Google, so there is no plan to make Dialogflow  work.  Getting Dialogflow to work with Node Red is not a straightforward exercise and doesn't provide much benefit.  Have a look at node-red-contrib-ecolect if you need a node to understand commands and questions (which is what Dialogflow provides).
